### ISSUE TITLE
run init in .zshrc

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/Comonicon.jl#40]
we need to add `autoload -Uz compinit && compinit` to `.zshrc` in some way, or the auto completion won't be enabled.

**Comment by mehalter** [comment]
I think the best way would be to use some regex to check if the users config is already calling these in their config and put it in if its missing, or ignore if its there.

Another option would be to print to the user the lines they need to add to make sure the auto completion is enabled if we detect `zsh` shell is being used and leave it up to the user. A lot of shell programs take this approach of 1. install all the correct files, 2. instruct user what they need to do when it comes to editing their shell system config files. There are trade offs for both approaches, it seems like the "julia" way is to try and make things as easy for the user as possible. If we do edit the configs, you could also do a message that notifies what lines/files were changed just for user awareness of their system configuration files.

**Comment by Roger-luo** [comment]
I see. I also prefer the later one, given that we cannot prompt anything during Julia's build.

But I'm not sure if people are OK to let us manipulate their config files since it might require a manual revise if they don't want to. Tho in my personal opinion on adding `PATH`, `FPATH` as well as this one to the config file is not a big deal.

So I guess maybe we should just let this issue open when more people start using this and see what they prefer. And before this is built into Comonicon's build system, we could add a line to tell people how to enable auto completion (this is also what `git` CLI does I think)
