### ISSUE TITLE
Non-Interactive PATH and FPATH Set Up

### ISSUE THREAD

**Issue by mehalter** [Roger-luo/Comonicon.jl#42]
Now that `PATH` and `FPATH` are not being done interactively when not in an interactive session, it seems like you cannot have a build script run using `julia --project deps/build.jl` to set up the `PATH` or `FPATH` even when it is specified explicitly in the arguments. I think it would be best to move the interactive check inside of the `install_env_path` and `install_completion` functions where if `quiet` or `!isinteractive()`, then it takes the default or specified value, or if it is `!quiet && isinteractive()` and nothing is specified manually, then ask.

I think if this approach is taken, it would make sense that by default it does nothing (default `export_path, completions = false, false`) and if they are specified (either are set to `true`) then you don't need to ask even if its interactive. I think this would help make it more explicit to the user when things will be changed in the system especially when using `--quiet` flag.

Now that I think about it, if you decide to default to `false`, there might not be a need for a `quiet` flag other than to do less verbose output/no output which is how it is normally used.

Let me know what you think of these ideas and if you want, I can help get the ball rolling with these changes!

Also thanks for being so responsive and quick to replying/changing stuff! This project is looking great!

**Comment by Roger-luo** [comment]
I think this is kinda related to #40 about how we want to install the commands and PATH into the system. I just send a twitter to see if people has an opinion on this too: https://twitter.com/rogerluorl18/status/1291124463115931648?s=20. 

I had some changes last week on the installation, now for CLI developers, they could specify the options via a config file, e.g in IonCLI, it's specified here: https://github.com/Roger-luo/IonCLI.jl/blob/master/Comonicon.toml

when I was writing this part, it was not actually clear to me how should we install these. And I'm also thinking in non-interactive mode, all `prompt` should always just return `false`? which means if the develops are not sure on this, just don't do it.

Then we could just remove the `isinteractive` check and we could check the `quiet` flag in the `install_env_path` and `install_completion` function, to silently choose yes (or it should be called `-y, --yes` to be more explicit).
what do you think?

> Also thanks for being so responsive and quick to replying/changing stuff! This project is looking great!

I can't build a perfect CLI generator alone, but with the community, we can!

**Comment by mehalter** [comment]
I like the idea of removing the interactivity, so like if you want to installed path and completions you give it the appropriate arguments and it will do it, if not don't do anything with it or prompt. Then we wouldn't need to include any prompts at all.

Also, I think I like

**Comment by Roger-luo** [comment]
OK, I guess according to the twitter poll, we will not install PATH/FPATH either silently or via prompt. But ask the user to install it themselves via an explicit command `comonicon_install_path` (which has been implemented in https://github.com/Roger-luo/Comonicon.jl/commit/ae152f21c17ea27e3335e34c538a3b57aafccd9e). I will shortly provide a CLI project template (implemented as a standard PkgTemplate plugin) in Ion.

Now I think we should just remove all the prompts during the installation.

**Comment by Roger-luo** [comment]
I think at least the behaviour of `] build` and `julia --project deps/build.jl` will at least become the same in this way. And user can always install path using the generated `Mod.comonicon_install_path()` command. 

to summary:

1. `quiet` will be used to disable logging
2. all prompt will be removed, `install` will not handle `PATH/FPATH` at all.
3. downstream CLI packages should update `README`s to mention how to install `PATH/FPATH` via the generated no argument function `comonicon_install_path`

**Comment by mehalter** [comment]
Ah I like that a lot more. I'm definitely a fan of not editing system files at all, but the general Julia ecosystem does it a lot to make the language more approachable to a wider range of users. I'm glad this is going to take a different approach.
