### ISSUE TITLE
Complex syntax in function def seems to be broken

### ISSUE THREAD

**Issue by xukai92** [Roger-luo/Comonicon.jl#53]
```julia
@cast function f(x=true; y=(x? +1 : -1))
    ...
end
```

gives

```
ERROR: LoadError: LoadError: TypeError: non-boolean (String) used in boolean context
```

**Comment by Roger-luo** [comment]
I think this is a convention, that by default an argument without annotation will not be converted automatically which will be a `String`. Note `f("false")` is a legal input for your declaration.

**Comment by Roger-luo** [comment]
If you are pretty sure `x` is a Boolean, it should be

```
@cast function f(x::Bool=true; y = x ? + 1 : - 1)
end
```

**Comment by xukai92** [comment]
This makes sense! Thanks!
