### ISSUE TITLE
to be honest the front page is very confusing

### ISSUE THREAD

**Issue by xiaodaigh** [Roger-luo/Comonicon.jl#54]
After reading the front page I still don't know how to make a cli.

Seems to have lots of details that's distracting like `➜  Comonicon git:(master)` What's that for? It's master branch of your package. But it doesn't help me understand how to make a cli? 

A simple step by step guide on how to make a CLI would be nice.

**Comment by Roger-luo** [comment]
I think as for the front page, it's more for showing off the features first, thus I put some benchmarks using `hyperfine`.

have you read https://rogerluo.me/Comonicon.jl/dev/#Quick-Start ? this is the document, does this help?

**Comment by Roger-luo** [comment]
I hope this is resolved by https://github.com/Roger-luo/Comonicon.jl/commit/512a4de2ad577849f1701fc6609b9a43fcc50c80 there really any more steps you need to create your first CLI. Just copy what's in the code block of getting started, and run `julia main.jl -h`, it will print help msg and that's it.

**Comment by Roger-luo** [comment]
I'm closing this for now, but feel free to ask other questions.
