### ISSUE TITLE
RFC: default system image building behaviour

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/Comonicon.jl#59]
we currently won't build the system image by default, if the download fails, so that we can throw a nice error msg during building to the REPL and let users to build it manually via a generated function `XX.comonicon_build()`. I'd like to discuss whether we should keep this behavior or do something else, especially given that we are not able to build system images for MacOS (https://github.com/Roger-luo/IonCLI.jl/issues/24)

**Comment by johnnychen94** [comment]
building sysimage as a fallback solution is not the key problem here.

Take the example of `IonCLI`, we should either provide a way to use `IonCLI` without sysimage, or provide better sysimage support/coverage.

**Comment by Roger-luo** [comment]
for a complicated CLI application like IonCLI, it will take a lot of time to start, I think fallback to local system build should be a better workaround.

> provide better sysimage support/coverage.

The main issue is PackageCompiler cannot generate the correct system image on GitHub action, and I'm not sure about why. Yeah, I agree if we treat the downloaded system image as an optimization, then building locally is something acceptable. I'll bring back the old behaviour on this.

**Comment by Roger-luo** [comment]
on the other hand, I think eventually we are going to make IonCLI a self-contained executable, which means it will ship with a small `libjulia` so I think all these issues won't happen for IonCLI side in the future, but I still need to wait for the progress of PackageCompiler.

**Comment by johnnychen94** [comment]
It seems that this still doesn't work:

```julia
┌ Error: Error building `IonCLI`:
│ ERROR: LoadError: ArgumentError: Package Test not found in current path:
│ - Run `import Pkg; Pkg.add("Test")` to install the Test package.
│
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:893
│  [2] include(::Function, ::Module, ::String) at ./Base.jl:380
│  [3] include(::Module, ::String) at ./Base.jl:368
│  [4] exec_options(::Base.JLOptions) at ./client.jl:296
│  [5] _start() at ./client.jl:506
│ in expression starting at /Users/jc/.julia/packages/IonCLI/04Jl6/test/runtests.jl:3
│ ┌ Error: Download failed: curl: (22) The requested URL returned error: 404 Not Found
│ └ @ Base download.jl:43
│ ┌ Warning: fail to download https://github.com/Roger-luo/IonCLI.jl/releases/download/v0.5.0/ion-1.5.1-darwin-x86_64.tar.gz, building the system image locally
│ └ @ Comonicon.BuildTools ~/.julia/packages/Comonicon/aSFTN/src/tools/build.jl:295
```

**Comment by Roger-luo** [comment]
Yeah, this is because when building system image, we will execute tests to generate precompile statements. I just updated IonCLI, can you check if this works for you now?

**Comment by johnnychen94** [comment]
Great! It works now. 🎉
