### ISSUE TITLE
Error when displaying regex in description

### ISSUE THREAD

**Issue by jakobnissen** [Roger-luo/Comonicon.jl#83]
I have a script where I want to add something like this to the program description:
```
Parses filenames. Files must match pattern ^([^_]+_S\d+)_L001_R(1|2)_001.fastq.gz$
```
However, if I copy-paste the regex string directly into the description, it interprets the regex as markdown. Fair enough. However, if instead I interpolate the regex string in, like this:
```
"""
Foos the filepath.
* Files must match pattern $REGEX
"""
@main function foo(x)
    [ ... ]
``` 
Then it displays:
```
Foos the filepath
    •    Files must match pattern
        r"^([^_]+S\d+)L001R(1|2)001.fastq.gz:($(Expr(:incomplete,
        "incomplete: invalid string syntax")))
```

**Comment by Roger-luo** [comment]
Hi @jakobnissen  I investigate this issue a bit today, it seems not an issue for Comonicon, but an issue for Julia's Markdown parser itself. If you don't annotate this with `@main` 

```julia
"""
Foos the filepath.
* Files must match pattern $REGEX
"""
function foo(x)
    [ ... ]
end
```

it still gives you this doc string, what Comonicon does is just to reparse whatever Julia's Markdown parser produce. 

even if you just manually copy pasta it, it gives this error too

```julia
raw"""
       Foos the filepath.
       * Files must match pattern r\"^([^_]+_S\\d+)_L001_R(1|2)_001.fastq.gz\$\"
"""
function goo(x)
end
```

**Comment by Roger-luo** [comment]
actually I believe this is not a Julia issue either, you missed code block mark in the docstring. 

```julia
julia> using Comonicon

julia> Comonicon.disable_cache()

julia> REGEX = r"^([^_]+_S\d+)_L001_R(1|2)_001.fastq.gz$"
r"^([^_]+_S\d+)_L001_R(1|2)_001.fastq.gz$"

julia> """
       Foos the filepath.
       * Files must match pattern `$REGEX`
       """
       @main function foo(x)
       end

  foo

  Foos the filepath.

    •    Files must match pattern
        r"^([^_]+_S\d+)_L001_R(1|2)_001.fastq.gz$"

Usage

  foo <x>

Args

  <x>

Flags

  -h, --help       print this help message

  -V, --version    print version information


```
