### ISSUE TITLE
Nested commands in a command line interface

### ISSUE THREAD

**Issue by 00krishna** [Roger-luo/Comonicon.jl#88]
Hello, I was just starting to look at Julia tools to help build command line interfaces. I was wondering if it is possible to create nested commands in an app. For example, if I wanted to create something like the `docker` CLI, then there are nested commands like `docker run` and `docker ps`, among others. I was just wondering if `comonicon` can handle something like this yet, or if this is an enhancement request. Thanks so much.

**Comment by Roger-luo** [comment]
Hi yes it can, please follow the tutorial: https://rogerluo.me/Comonicon.jl/dev/project/

to be short - nested commands are just julia `module`s. I'm closing this, but feel free to open new issues.
